### ISSUE TITLE
pretrained model error

### ISSUE THREAD

**Issue by pradeepkc11** [eurecom-asp/RawGAT-ST-antispoofing#7]
cache_fname cache_eval_LA_Raw_GAT.npy
Traceback (most recent call last):
  File "/home/pradeep/.local/lib/python3.10/site-packages/torch/serialization.py", line 619, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol, _disable_byteorder_record)
  File "/home/pradeep/.local/lib/python3.10/site-packages/torch/serialization.py", line 853, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:588] . PytorchStreamWriter failed writing file data/51697: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pradeep/RawGAT-ST-antispoofing/main.py", line 228, in <module>
    dev_set = data_utils.ASVDataset(database_path=args.database_path,protocols_path=args.protocols_path,is_train=False, is_logical=is_logical,
  File "/home/pradeep/RawGAT-ST-antispoofing/data_utils.py", line 106, in __init__
    torch.save((self.data_x, self.data_y, self.data_sysid, self.files_meta), self.cache_fname)
  File "/home/pradeep/.local/lib/python3.10/site-packages/torch/serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/home/pradeep/.local/lib/python3.10/site-packages/torch/serialization.py", line 466, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:424] . unexpected pos 11996555136 vs 11996555000

**Comment by TakHemlata** [comment]
Hi @pradeepkc11 I think this error is related to Pytorch new version. Regarding second error you have to use correct path for development protocol so that will save correct file name for feature extraction.

I suggest that you can use data-loader part and main script from this repo (https://github.com/asvspoof-challenge/2021/tree/main/LA/Baseline-RawNet2)  with RawGAT-ST model script. Much more simple data-loader script.

Please let me know if it works for you.

Thanks
